### ISSUE TITLE
TLS and keys

### ISSUE THREAD

**Issue by stefhak** [EricssonResearch/blind-cache-draft#14]
Should there be some text about prerequisites for a UA to propose an oob cache to the origing (related to certificates/keys used to establish a TLS connection to the cache)?

**Comment by gaperik** [comment]
This is an area that needs more exploration. One aspect is that the discovery need to be "secure", something that is touched upon in the current version. Another is as you say the TLS connection to the jib cache- I was thinking to follow the example of Alt Service in this respect. Then the question is if this is an "issue" with the oob draft also, https://github.com/reschke/oobencoding...
